### ISSUE TITLE
doc style pull request

### ISSUE THREAD

**Issue by burningTyger** [mendicant-original/ruby#1]
I sent a pull request to ruby/ruby because for some reason rmu/ruby did not show up in my list of possible repos where I'd like to send my pull request to. Please see it here: https://github.com/ruby/ruby/pull/49 and let me know what you think.

**Comment by semmons99** [comment]
I believe that is because you forked ruby/ruby and not rmu/ruby.

**Comment by semmons99** [comment]
Looking at the documentation. It looks good to me. Do you need help creating a patch to submit to Ruby Core?

**Comment by burningTyger** [comment]
yea, I noticed that but when I clicked the pull request button I could change my settings to point it to various other repos but not the rmu one. Probably one of those edge cases that nobody really uses anyway :)

Patch is here now: http://redmine.ruby-lang.org/issues/5393

**Comment by practicingruby** [comment]
@burningTyger: Thanks! Closing the ticket here, please re-open if you need us to review any changes requested upstream.
