### ISSUE TITLE
Working on improving Time documentation

### ISSUE THREAD

**Issue by semmons99** [mendicant-original/ruby#6]
I will be working on improving the Time documentation.

**Comment by semmons99** [comment]
I [just opened a ticket](http://redmine.ruby-lang.org/issues/5402) with my enhanced documentation for the Time extension in stdlib. Now working on documenting the core Time class.

**Comment by ericgj** [comment]
Definitely needed, great!

**Comment by semmons99** [comment]
[Enhanced the documentation](http://redmine.ruby-lang.org/issues/5404) for the Time class in core!
